def forward (dis):
 motor_1.set_velocity(50, PERCENT)
 motor_10.set_velocity(50, PERCENT)
 motor_11.set_velocity(50, PERCENT)
 motor_20.set_velocity(50, PERCENT)
 motor_1.spin(REVERSE)
 motor_10.spin(FORWARD)
 motor_11.spin(REVERSE)
 motor_20.spin(FORWARD)
 wait(0.3,SECONDS)
 motor_1.set_velocity(50, PERCENT)
 motor_10.set_velocity(50, PERCENT)
 motor_11.set_velocity(50, PERCENT)
 motor_20.set_velocity(50, PERCENT)
 motor_1.spin(REVERSE)
 motor_10.spin(FORWARD)
 motor_11.spin(REVERSE)
 motor_20.spin(FORWARD)
 wait(dis,SECONDS)
 motor_1.stop()
 motor_10.stop()
 motor_11.stop()
 motor_20.stop()
def right (right):
 motor_1.set_velocity(50, PERCENT)
 motor_10.set_velocity(50, PERCENT)
 motor_11.set_velocity(50, PERCENT)
 motor_20.set_velocity(50, PERCENT)
 motor_1.spin_for(FORWARD, right, DEGREES,wait=False)
 motor_10.spin_for(FORWARD, right, DEGREES,wait=False)
 motor_11.spin_for(FORWARD, right, DEGREES,wait=False)
 motor_20.spin_for(FORWARD, right, DEGREES, wait=False)

motor_12.set_velocity(100, PERCENT)           
motor_19.spin_for(FORWARD, 50, DEGREES)
wait(1,SECONDS)
motor_12.spin(FORWARD)
wait(1,SECONDS)
forward(0.09)
wait(1,SECONDS)
motor_12.spin(REVERSE)
wait(1,SECONDS)
motor_19.spin_for(FORWARD, 120, DEGREES)
wait(1,SECONDS)
right(1450)
wait(3,SECONDS)
forward(0.1 )
wait(1,SECONDS)
motor_19.set_velocity(75, PERCENT)
motor_19.spin_for(REVERSE, 120, DEGREES)
wait(1,SECONDS)
motor_12.spin(FORWARD)
wait(1.5,SECONDS)
motor_1.spin(FORWARD)
motor_10.spin(REVERSE)
motor_11.spin(FORWARD)
motor_20.spin(REVERSE)
wait(0.8,SECONDS)
motor_1.stop()
motor_10.stop()
motor_11.stop()
motor_20.stop()
wait(1,SECONDS)
motor_19.spin_for(FORWARD, 100, DEGREES)
